### PR TITLE
DP-483

### PR DESCRIPTION
**Pull request by JordanBalesBAO**
Relates to ticket DP-483
Created PR against master since dev looked out of date, hope that is okay.

### CODE REVIEW

**Comment by sam-bao** [comment]
@JordanBalesBAO Can you add unit tests related to these new error messages?

**Comment by JordanBalesBAO** [comment]
@sam-bao on it.

**Comment by JordanBalesBAO** [comment]
@sam-bao got some unit tests together, and are ready for review. Wasn't sure how to create the mocks for dhis2 being down or under maintenance.

**Comment by JordanBalesBAO** [comment]
@sam-bao made the additions we discussed this morning, should be ready to review.

**Comment by JordanBalesBAO** [comment]
@sam-bao Removed the misplaced response file. I also cleaned up as much linting as I felt comfortable doing. Some of them  involved renaming variables and removing comments.

**Review by sam-bao — APPROVED** [review]
@jason-p-pickering This looks good to go into master to me. New code is unit tested and linted. Maybe you want to take a quick look as UAT as I think you requested and/or documented the feature.

**Review by jason-p-pickering — APPROVED** [review]

**Pull request merged**
