### PR TITLE
Gh 712 20200520

### PR DESCRIPTION
**Pull request by sam-bao**
@maxwellchandler This implements mocks for the getOrgUnitGroup tests.

Additionally I made a small modification to the test for the API call with duplicates to make sure it is returning results in a way that maps directly to the input list. This test is not passing.

So if orgUnitGroup names A has uid: 11111111111 and B has uid 22222222222

So if I make a call to getOrgUnitGroups with c(11111111111, 11111111111, 22222222222) I should get back A, A, B.

### CODE REVIEW

**Comment by maxwellchandler** [comment]
@sam-bao that is going to be more complicated than it seems because thats how datim returns the data. 
"https://play.dhis2.org/2.33/api/organisationUnitGroups.json?paging=false&filter=id:in:[gzcv65VyaGq,uYxK4wmcPqA,RXL3lPSK8oG,RpbiCJpIYEj,w1Atoz18PCL,CXw2yu5fodb]&fields=id"
returns
$organisationUnitGroups
           id
1 CXw2yu5fodb
2 gzcv65VyaGq
3 uYxK4wmcPqA
4 RXL3lPSK8oG
5 RpbiCJpIYEj
6 w1Atoz18PCL
 and you can see its not in order so it will take some extra code to make this ordering work

**Comment by jason-p-pickering** [comment]
I think you should really compare the content of the unique set instead. Ordering will never be guaranteed with an API response from DHIS2. Also pretty sure thay if you have a duplicate UID in the filter, you are not going to get a duplicated result.

**Comment by sam-bao** [comment]
@maxwellchandler right, you need to implement code ensure the return object matches the request. The idea is that these helper functions (getOrgUnits, getOrgUnitGroups, getDataElements, etc) should be able to be used easily in a dplyr::mutate statement for instance:

```
data_with_uid_col %>%
 dplyr::mutate(org_unit_name = getOrgUnits(uid_col, fields = "name"))
```

This only works if the response from getOrgUnits is the same length and order as the elements of uid_col.

Some pseudo code for this:

getOrgUnitGroups(filter = uid_list, fields = "name") #by = id by default

   filter_unique = unique(filter)
   if by property not in fields add it when calling api, call api with unigue_filter list
   left join api response to original filter list (this matches and orders)
   if we had to add the by property was added to fields by the function, remove the column   
  

Please see my comment here: https://github.com/pepfar-datim/COP-Target-Setting/issues/747#issuecomment-629202673

**Comment by maxwellchandler** [comment]
@sam-bao if thats the case then its working as intended right now with my last push

**Pull request merged**
