### PR TITLE
DP-132: Add `convertFYQuarterCalendarQuarter`

### PR DESCRIPTION
**Pull request by maxwellchandler**

### CODE REVIEW

**Comment by sam-bao** [comment]
@jason-p-pickering for this datimutils function that converts a PEPFAR FY quarter to a calendar quarter, do you think providing a period e.g. 2020Q1 should also be supported?

Any need for a function that goes in the opposite direction?

**Comment by jason-p-pickering** [comment]
@sam-bao yeah, I think that would make sense as well.

**Review by JordanBalesBAO — COMMENTED** [review]
@cnemarich this looks good to me. Are we okay with the long function name in terms of our style guide?

**Comment by cnemarich** [comment]
@JordanBalesBAO, good point. Any suggestions on a shorter function name?

**Comment by JordanBalesBAO** [comment]
@cnemarich  hmmm. What about convertQuarter() or convertFYQToCQ()? Im also fine with leaving it convertFYQuarterCalendarQuarter for context reasons, but it is long.

**Review by JordanBalesBAO — APPROVED** [review]
Approving after my updates, @cnemarich you can take a quick peek at my updates, but all were just vanity changes.

**Pull request merged**
