### PR TITLE
Gh712 xtra unit tests

### PR DESCRIPTION
**Pull request by sam-bao**
@maxwellchandler 

This pull requests adds a number of tests for the api_get function.

One is not passing. 

```
> test()
Loading datimutils
Testing datimutils
✓ |  OK F W S | Context
x |  13 1     | make arbitrary api call DATIM [0.4 s]
─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
test-api_get.R:76: error: basic calls: https://play.dhis2.org/2.33/api/me.json?paging=false
GET https://play.dhis2.org/2.33/api/me.json.json?paging=false (play.dhis2.org/2.33/api/me.json.json-3b3c4f.json)
Backtrace:
 1. datimutils::api_get(path = "api/me.json", base_url = "https://play.dhis2.org/2.33/") tests/testthat/test-api_get.R:76:4
 2. httr::GET(url, httr::timeout(timeout)) R/callDATIMapi.R:47:4
 3. httr:::request_perform(req, hu$handle$handle)
 4. httr:::request_fetch(req$output, req$url, handle)
 6. httptest:::stop_request(req)
─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
✓ |   1       | make arbitrary api call DATIM
✓ |   1       | make arbitrary api call with getorgunits

══ Results ══════════════════════════════════════════════════════════════════════════════════════════════════════════════════
Duration: 0.5 s

OK:       15
Failed:   1
Warnings: 0
Skipped:  0
```

### CODE REVIEW

**Comment by maxwellchandler** [comment]
Ok ill make it pass, it probably has something to do with the mock api file

**Comment by sam-bao** [comment]
@maxwellchandler I don't think the issue is with the mock, this is the api call made by the api_get function `https://play.dhis2.org/2.33/api/me.json.json?paging=false `.

The .json is doubled.

**Comment by maxwellchandler** [comment]
I see. Was this branched off of my latest commits to 712? If not I will have to make some changes to the function.

**Comment by sam-bao** [comment]
Actually this seems to work when called: `https://play.dhis2.org/2.33/api/me.json.json?paging=false`

But, I I would still like to see: `https://play.dhis2.org/2.33/api/me.json?paging=false`

**Comment by maxwellchandler** [comment]
I see. I built the function with the intent that it would never be used directly, and so i never anticipated anyone passing in .json?pagin=false in the actual url. So i will have to take that into account in the function

**Comment by sam-bao** [comment]
I rebased.

**Comment by sam-bao** [comment]
@maxwellchandler 

The list of possible response formats for a DHIS2 api call is     ".jsonp", ".html", ".xml", ".pdf",
    ".xls", ".csv", ".html+css", ".adx" and of course ".json"

Your approach to assume .json for this internal function makes sense to me, but we should trap requests for the other formats as errors. I have added a unit test that does this 
```
# no mock for this test - no httr requests should actually be issued
# for these resonse formats
# we expect only json requests
test_that("We reject request for non-json response formats", {
  formats <- c(
    ".jsonp", ".html", ".xml", ".pdf",
    ".xls", ".csv", ".html+css", ".adx"
  )
  helper <- function(x) {
    # we should get an error for unsupported response format in URL
    expected_error <- expect_error(
      api_get(
        path = paste0(
          "api/analytics", x,
          "?dimension=dx:fbfJHSPpUQD",
          "&dimension=pe:LAST_12_MONTHS",
          "&filter=ou:ImspTQPwCqd"
        ),
        base_url = "https://play.dhis2.org/2.33/"
      )
    )
    # when run with_internet the error message should start with GET
    # see details of httptest::with_internet
    expect_false(grepl("GET ", expected_error$message))
  }
  without_internet(lapply(formats, helper))
})
```

This unit test checks for an error, and also makes sure that an api call is not actually issued when an unsupported format is requested.

Additionally this test is still failing:

```
test-api_get.R:106: error: basic calls: https://play.dhis2.org/2.33/api/me.json?paging=false
GET https://play.dhis2.org/2.33/api/me.json (play.dhis2.org/2.33/api/me.json.json)
Backtrace:
 1. datimutils::api_get(path = "api/me.json", base_url = "https://play.dhis2.org/2.33/") tests/testthat/test-api_get.R:106:4
 2. httr::GET(url, httr::timeout(timeout)) R/callDATIMapi.R:56:4
 3. httr:::request_perform(req, hu$handle$handle)
 4. httr:::request_fetch(req$output, req$url, handle)
 6. httptest:::stop_request(req)
```

This was passing but only because there was a mock for this call `play.dhis2.org/2.33/api/me.json.json`. I removed this mock because this is not a well formed URL even though it will provide a valid api response.  

You should not need to add any mocks as a result of the changes in this pull request. If you believe you do, please let me know.

**Comment by maxwellchandler** [comment]
@sam-bao  That actually is a well formed link. Remember that it is looking for a mock file with the extention .json, so the link is effectively play.dhis2.org/2.33/api/me.json

**Comment by sam-bao** [comment]
@maxwellchandler I believe I correctly deleted the mock and that the call in the error above is incorrect. The url in the actual request should end with `?paging=false` if I understood your code correctly.

So in the test I call 
```
 api_get(
      path = "api/me.json",
      base_url = "https://play.dhis2.org/2.33/"
    )
```

the actual call I was expecting was `https://play.dhis2.org/2.33/api/me.json?paging=false`

**Comment by maxwellchandler** [comment]
@sam-bao Ok I see, I see, ill look into that

**Comment by sam-bao** [comment]
And to the other point, I would prefer to actually trap this as an error instead of altering the .csv or any other response formats to .json. 

Modifying the .csv (or .adx...) to .json feels a little bit like breaking a contract, even though we are sending a data frame back anyway.  Practically, as we use api_get we will just leave off the .json and the paging = false, right. But, fundamentally the function uses .json so it shouldn't accept requests for other response formats.

**Comment by maxwellchandler** [comment]
@sam-bao Ok thats fine. We do have some "csv" response mock files so those are getting special treatment, and If we error path all other formats besides json we might have to change those csv tests, but other than that I think I have enough info to make some commits on this branch. I will error out the other routes and fix the api_function to work with the tests without creating new mock files.

**Comment by sam-bao** [comment]
@maxwellchandler I think that .csv route was only working because the me endpoint returns json no matter what response format you request.

If you put this into your browser `https://play.dhis2.org/2.33.3/api/indicators.csv.json&paging=false` you will see you actually get back XML.

**Comment by maxwellchandler** [comment]
@sam-bao ok so just to be clear: do you want csv to be a valid route or do you want anything that is not json to go into an error route? If everything goes into the error route we can delete the mock tests for the csv urls and use the new test you made above,

**Comment by sam-bao** [comment]
I already removed the other mocks. The function should continue only if there is no requested response format or the requested response format should be .json.

**Pull request merged**
